public interface com.picotrading.tech.madase.mmap.MarketDataMmapAccessable {
    public Long getTimestamp(java.nio.ByteBuffer, Integer);
    public Long getTimestamp(java.nio.ByteBuffer);
    public Long putTimestamp(java.nio.ByteBuffer, Long, Integer);
    public Long putTimestamp(java.nio.ByteBuffer, Long);
    public Integer lengthTimestamp();
    public Integer offsetTimestamp();
    public Integer positionTimestamp(Integer);
    public Long getQuoteTime(java.nio.ByteBuffer, Integer);
    public Long getQuoteTime(java.nio.ByteBuffer);
    public Long putQuoteTime(java.nio.ByteBuffer, Long, Integer);
    public Long putQuoteTime(java.nio.ByteBuffer, Long);
    public Integer lengthQuoteTime();
    public Integer offsetQuoteTime();
    public Integer positionQuoteTime(Integer);
    public Long getTradeTime(java.nio.ByteBuffer, Integer);
    public Long getTradeTime(java.nio.ByteBuffer);
    public Long putTradeTime(java.nio.ByteBuffer, Long, Integer);
    public Long putTradeTime(java.nio.ByteBuffer, Long);
    public Integer lengthTradeTime();
    public Integer offsetTradeTime();
    public Integer positionTradeTime(Integer);
    public Object getQuoteCondition(java.nio.ByteBuffer, Integer);
    public Object getQuoteCondition(java.nio.ByteBuffer);
    public Object putQuoteCondition(java.nio.ByteBuffer, Object, Integer);
    public Object putQuoteCondition(java.nio.ByteBuffer, Object);
    public Integer lengthQuoteCondition();
    public Integer offsetQuoteCondition();
    public Integer positionQuoteCondition(Integer);
    public Object getTradeCondition(java.nio.ByteBuffer, Integer);
    public Object getTradeCondition(java.nio.ByteBuffer);
    public Object putTradeCondition(java.nio.ByteBuffer, Object, Integer);
    public Object putTradeCondition(java.nio.ByteBuffer, Object);
    public Integer lengthTradeCondition();
    public Integer offsetTradeCondition();
    public Integer positionTradeCondition(Integer);
    public Float getBid(java.nio.ByteBuffer, Integer);
    public Float getBid(java.nio.ByteBuffer);
    public Float putBid(java.nio.ByteBuffer, Float, Integer);
    public Float putBid(java.nio.ByteBuffer, Float);
    public Integer lengthBid();
    public Integer offsetBid();
    public Integer positionBid(Integer);
    public Float getAsk(java.nio.ByteBuffer, Integer);
    public Float getAsk(java.nio.ByteBuffer);
    public Float putAsk(java.nio.ByteBuffer, Float, Integer);
    public Float putAsk(java.nio.ByteBuffer, Float);
    public Integer lengthAsk();
    public Integer offsetAsk();
    public Integer positionAsk(Integer);
    public Float getLast(java.nio.ByteBuffer, Integer);
    public Float getLast(java.nio.ByteBuffer);
    public Float putLast(java.nio.ByteBuffer, Float, Integer);
    public Float putLast(java.nio.ByteBuffer, Float);
    public Integer lengthLast();
    public Integer offsetLast();
    public Integer positionLast(Integer);
    public Integer getBidSize(java.nio.ByteBuffer, Integer);
    public Integer getBidSize(java.nio.ByteBuffer);
    public Integer putBidSize(java.nio.ByteBuffer, Integer, Integer);
    public Integer putBidSize(java.nio.ByteBuffer, Integer);
    public Integer lengthBidSize();
    public Integer offsetBidSize();
    public Integer positionBidSize(Integer);
    public Integer getAskSize(java.nio.ByteBuffer, Integer);
    public Integer getAskSize(java.nio.ByteBuffer);
    public Integer putAskSize(java.nio.ByteBuffer, Integer, Integer);
    public Integer putAskSize(java.nio.ByteBuffer, Integer);
    public Integer lengthAskSize();
    public Integer offsetAskSize();
    public Integer positionAskSize(Integer);
    public Integer getLastSize(java.nio.ByteBuffer, Integer);
    public Integer getLastSize(java.nio.ByteBuffer);
    public Integer putLastSize(java.nio.ByteBuffer, Integer, Integer);
    public Integer putLastSize(java.nio.ByteBuffer, Integer);
    public Integer lengthLastSize();
    public Integer offsetLastSize();
    public Integer positionLastSize(Integer);
    public Float getVwap(java.nio.ByteBuffer, Integer);
    public Float getVwap(java.nio.ByteBuffer);
    public Float putVwap(java.nio.ByteBuffer, Float, Integer);
    public Float putVwap(java.nio.ByteBuffer, Float);
    public Integer lengthVwap();
    public Integer offsetVwap();
    public Integer positionVwap(Integer);
    public Object getCondition(java.nio.ByteBuffer, Integer);
    public Object getCondition(java.nio.ByteBuffer);
    public Object putCondition(java.nio.ByteBuffer, Object, Integer);
    public Object putCondition(java.nio.ByteBuffer, Object);
    public Integer lengthCondition();
    public Integer offsetCondition();
    public Integer positionCondition(Integer);
    public Long getTotalAmount(java.nio.ByteBuffer, Integer);
    public Long getTotalAmount(java.nio.ByteBuffer);
    public Long putTotalAmount(java.nio.ByteBuffer, Long, Integer);
    public Long putTotalAmount(java.nio.ByteBuffer, Long);
    public Integer lengthTotalAmount();
    public Integer offsetTotalAmount();
    public Integer positionTotalAmount(Integer);
    public Integer getVolume(java.nio.ByteBuffer, Integer);
    public Integer getVolume(java.nio.ByteBuffer);
    public Integer putVolume(java.nio.ByteBuffer, Integer, Integer);
    public Integer putVolume(java.nio.ByteBuffer, Integer);
    public Integer lengthVolume();
    public Integer offsetVolume();
    public Integer positionVolume(Integer);
    public Object getCurrency(java.nio.ByteBuffer, Integer);
    public Object getCurrency(java.nio.ByteBuffer);
    public Object putCurrency(java.nio.ByteBuffer, Object, Integer);
    public Object putCurrency(java.nio.ByteBuffer, Object);
    public Integer lengthCurrency();
    public Integer offsetCurrency();
    public Integer positionCurrency(Integer);
    public Long getLatency(java.nio.ByteBuffer, Integer);
    public Long getLatency(java.nio.ByteBuffer);
    public Long putLatency(java.nio.ByteBuffer, Long, Integer);
    public Long putLatency(java.nio.ByteBuffer, Long);
    public Integer lengthLatency();
    public Integer offsetLatency();
    public Integer positionLatency(Integer);
    public Long getInternalLatency(java.nio.ByteBuffer, Integer);
    public Long getInternalLatency(java.nio.ByteBuffer);
    public Long putInternalLatency(java.nio.ByteBuffer, Long, Integer);
    public Long putInternalLatency(java.nio.ByteBuffer, Long);
    public Integer lengthInternalLatency();
    public Integer offsetInternalLatency();
    public Integer positionInternalLatency(Integer);
    public String getSymbol(java.nio.ByteBuffer, Integer);
    public String getSymbol(java.nio.ByteBuffer);
    public String putSymbol(java.nio.ByteBuffer, String, Integer);
    public String putSymbol(java.nio.ByteBuffer, String);
    public Integer lengthSymbol();
    public Integer offsetSymbol();
    public Integer positionSymbol(Integer);
}

