public interface com.picotrading.tech.madase.mmap.MarketDataMmapAccessable {
    public abstract java.lang.Long getTimestamp(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Long getTimestamp(java.nio.ByteBuffer);
    public abstract java.lang.Long putTimestamp(java.nio.ByteBuffer, java.lang.Long, java.lang.Integer);
    public abstract java.lang.Long putTimestamp(java.nio.ByteBuffer, java.lang.Long);
    public abstract java.lang.Integer lengthTimestamp();
    public abstract java.lang.Integer offsetTimestamp();
    public abstract java.lang.Integer positionTimestamp(java.lang.Integer);
    public abstract java.lang.Long getQuoteTime(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Long getQuoteTime(java.nio.ByteBuffer);
    public abstract java.lang.Long putQuoteTime(java.nio.ByteBuffer, java.lang.Long, java.lang.Integer);
    public abstract java.lang.Long putQuoteTime(java.nio.ByteBuffer, java.lang.Long);
    public abstract java.lang.Integer lengthQuoteTime();
    public abstract java.lang.Integer offsetQuoteTime();
    public abstract java.lang.Integer positionQuoteTime(java.lang.Integer);
    public abstract java.lang.Long getTradeTime(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Long getTradeTime(java.nio.ByteBuffer);
    public abstract java.lang.Long putTradeTime(java.nio.ByteBuffer, java.lang.Long, java.lang.Integer);
    public abstract java.lang.Long putTradeTime(java.nio.ByteBuffer, java.lang.Long);
    public abstract java.lang.Integer lengthTradeTime();
    public abstract java.lang.Integer offsetTradeTime();
    public abstract java.lang.Integer positionTradeTime(java.lang.Integer);
    public abstract java.lang.Object getQuoteCondition(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Object getQuoteCondition(java.nio.ByteBuffer);
    public abstract java.lang.Object putQuoteCondition(java.nio.ByteBuffer, java.lang.Object, java.lang.Integer);
    public abstract java.lang.Object putQuoteCondition(java.nio.ByteBuffer, java.lang.Object);
    public abstract java.lang.Integer lengthQuoteCondition();
    public abstract java.lang.Integer offsetQuoteCondition();
    public abstract java.lang.Integer positionQuoteCondition(java.lang.Integer);
    public abstract java.lang.Object getTradeCondition(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Object getTradeCondition(java.nio.ByteBuffer);
    public abstract java.lang.Object putTradeCondition(java.nio.ByteBuffer, java.lang.Object, java.lang.Integer);
    public abstract java.lang.Object putTradeCondition(java.nio.ByteBuffer, java.lang.Object);
    public abstract java.lang.Integer lengthTradeCondition();
    public abstract java.lang.Integer offsetTradeCondition();
    public abstract java.lang.Integer positionTradeCondition(java.lang.Integer);
    public abstract java.lang.Float getBid(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Float getBid(java.nio.ByteBuffer);
    public abstract java.lang.Float putBid(java.nio.ByteBuffer, java.lang.Float, java.lang.Integer);
    public abstract java.lang.Float putBid(java.nio.ByteBuffer, java.lang.Float);
    public abstract java.lang.Integer lengthBid();
    public abstract java.lang.Integer offsetBid();
    public abstract java.lang.Integer positionBid(java.lang.Integer);
    public abstract java.lang.Float getAsk(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Float getAsk(java.nio.ByteBuffer);
    public abstract java.lang.Float putAsk(java.nio.ByteBuffer, java.lang.Float, java.lang.Integer);
    public abstract java.lang.Float putAsk(java.nio.ByteBuffer, java.lang.Float);
    public abstract java.lang.Integer lengthAsk();
    public abstract java.lang.Integer offsetAsk();
    public abstract java.lang.Integer positionAsk(java.lang.Integer);
    public abstract java.lang.Float getLast(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Float getLast(java.nio.ByteBuffer);
    public abstract java.lang.Float putLast(java.nio.ByteBuffer, java.lang.Float, java.lang.Integer);
    public abstract java.lang.Float putLast(java.nio.ByteBuffer, java.lang.Float);
    public abstract java.lang.Integer lengthLast();
    public abstract java.lang.Integer offsetLast();
    public abstract java.lang.Integer positionLast(java.lang.Integer);
    public abstract java.lang.Integer getBidSize(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Integer getBidSize(java.nio.ByteBuffer);
    public abstract java.lang.Integer putBidSize(java.nio.ByteBuffer, java.lang.Integer, java.lang.Integer);
    public abstract java.lang.Integer putBidSize(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Integer lengthBidSize();
    public abstract java.lang.Integer offsetBidSize();
    public abstract java.lang.Integer positionBidSize(java.lang.Integer);
    public abstract java.lang.Integer getAskSize(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Integer getAskSize(java.nio.ByteBuffer);
    public abstract java.lang.Integer putAskSize(java.nio.ByteBuffer, java.lang.Integer, java.lang.Integer);
    public abstract java.lang.Integer putAskSize(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Integer lengthAskSize();
    public abstract java.lang.Integer offsetAskSize();
    public abstract java.lang.Integer positionAskSize(java.lang.Integer);
    public abstract java.lang.Integer getLastSize(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Integer getLastSize(java.nio.ByteBuffer);
    public abstract java.lang.Integer putLastSize(java.nio.ByteBuffer, java.lang.Integer, java.lang.Integer);
    public abstract java.lang.Integer putLastSize(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Integer lengthLastSize();
    public abstract java.lang.Integer offsetLastSize();
    public abstract java.lang.Integer positionLastSize(java.lang.Integer);
    public abstract java.lang.Float getVwap(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Float getVwap(java.nio.ByteBuffer);
    public abstract java.lang.Float putVwap(java.nio.ByteBuffer, java.lang.Float, java.lang.Integer);
    public abstract java.lang.Float putVwap(java.nio.ByteBuffer, java.lang.Float);
    public abstract java.lang.Integer lengthVwap();
    public abstract java.lang.Integer offsetVwap();
    public abstract java.lang.Integer positionVwap(java.lang.Integer);
    public abstract java.lang.Object getCondition(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Object getCondition(java.nio.ByteBuffer);
    public abstract java.lang.Object putCondition(java.nio.ByteBuffer, java.lang.Object, java.lang.Integer);
    public abstract java.lang.Object putCondition(java.nio.ByteBuffer, java.lang.Object);
    public abstract java.lang.Integer lengthCondition();
    public abstract java.lang.Integer offsetCondition();
    public abstract java.lang.Integer positionCondition(java.lang.Integer);
    public abstract java.lang.Long getTotalAmount(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Long getTotalAmount(java.nio.ByteBuffer);
    public abstract java.lang.Long putTotalAmount(java.nio.ByteBuffer, java.lang.Long, java.lang.Integer);
    public abstract java.lang.Long putTotalAmount(java.nio.ByteBuffer, java.lang.Long);
    public abstract java.lang.Integer lengthTotalAmount();
    public abstract java.lang.Integer offsetTotalAmount();
    public abstract java.lang.Integer positionTotalAmount(java.lang.Integer);
    public abstract java.lang.Integer getVolume(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Integer getVolume(java.nio.ByteBuffer);
    public abstract java.lang.Integer putVolume(java.nio.ByteBuffer, java.lang.Integer, java.lang.Integer);
    public abstract java.lang.Integer putVolume(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Integer lengthVolume();
    public abstract java.lang.Integer offsetVolume();
    public abstract java.lang.Integer positionVolume(java.lang.Integer);
    public abstract java.lang.Object getCurrency(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Object getCurrency(java.nio.ByteBuffer);
    public abstract java.lang.Object putCurrency(java.nio.ByteBuffer, java.lang.Object, java.lang.Integer);
    public abstract java.lang.Object putCurrency(java.nio.ByteBuffer, java.lang.Object);
    public abstract java.lang.Integer lengthCurrency();
    public abstract java.lang.Integer offsetCurrency();
    public abstract java.lang.Integer positionCurrency(java.lang.Integer);
    public abstract java.lang.Long getLatency(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Long getLatency(java.nio.ByteBuffer);
    public abstract java.lang.Long putLatency(java.nio.ByteBuffer, java.lang.Long, java.lang.Integer);
    public abstract java.lang.Long putLatency(java.nio.ByteBuffer, java.lang.Long);
    public abstract java.lang.Integer lengthLatency();
    public abstract java.lang.Integer offsetLatency();
    public abstract java.lang.Integer positionLatency(java.lang.Integer);
    public abstract java.lang.Long getInternalLatency(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.Long getInternalLatency(java.nio.ByteBuffer);
    public abstract java.lang.Long putInternalLatency(java.nio.ByteBuffer, java.lang.Long, java.lang.Integer);
    public abstract java.lang.Long putInternalLatency(java.nio.ByteBuffer, java.lang.Long);
    public abstract java.lang.Integer lengthInternalLatency();
    public abstract java.lang.Integer offsetInternalLatency();
    public abstract java.lang.Integer positionInternalLatency(java.lang.Integer);
    public abstract java.lang.String getSymbol(java.nio.ByteBuffer, java.lang.Integer);
    public abstract java.lang.String getSymbol(java.nio.ByteBuffer);
    public abstract java.lang.String putSymbol(java.nio.ByteBuffer, java.lang.String, java.lang.Integer);
    public abstract java.lang.String putSymbol(java.nio.ByteBuffer, java.lang.String);
    public abstract java.lang.Integer lengthSymbol();
    public abstract java.lang.Integer offsetSymbol();
    public abstract java.lang.Integer positionSymbol(java.lang.Integer);
}

